### PR TITLE
Lab1

### PR DESCRIPTION
**Pull request by shampa077**
Fixes #

Review of colleague's PR #155

### CODE REVIEW

**Comment by shampa077** [comment]
fixed in next commit

**Comment by shampa077** [comment]
reviewed @hsy3418 lab1.

**Comment by kasunfdo** [comment]
You should have forked the repository as instructed.

**Comment by shampa077** [comment]
> You should have forked the repository as instructed.

@kasunfdo  Hi I followed the instruction.
what i have done wrong is git push --set-upstream origin lab1  (git suggested that)
instead of git push origin lab1.

**Comment by shampa077** [comment]
Review of colleague's PR #155

**Comment by kasunfdo** [comment]
Cool! I see you have forked. Sorry about that. What has gone wrong is you have pushed changes to the main repo (not to the forked one).

You should get following output with `git remote -v`command.

```
origin	https://github.com/shampa077/go-course.git (fetch)
origin	https://github.com/shampa077/go-course.git (push)
upstream	https://github.com/anz-bank/go-course (fetch)
upstream	https://github.com/anz-bank/go-course (push)
```

Changes should be pushed to forked repo as follows.
`git push origin lab1`

If you have done it right, following will be shown at the top of the pull request page. 

[shampa077]() wants to merge 5 commits into `anz-bank:master` from `shampa077:lab1`

I'm not nitpicking, but hope you will find this helpful. 😊

**Review by juliaogris — CHANGES_REQUESTED** [review]
@kasunfdo has it spot on. 
Please close this PR and start a new one from your fork. We will step on each other's toes if we all issue PRs with the same branch name from the same remote. 
Please come and see us before or after the talk if you have trouble - happy to help out.

Also, please fell in the PR description.

You can find more pointers in the [collected Lab1 review comments](https://github.com/anz-bank/go-course/wiki/Lab-1:-Collected-Code-Review-Comments)

**Pull request closed without merging**
