### PR TITLE
Lab-4,5 : Numeronyms and stringer interface

### PR DESCRIPTION
**Pull request by ShahNikita19**
Fixes #67

Changes proposed in this PR:
-Program to return numeronyms for a given set of strings
-Test cases for the program

Fixes #70
-Make IPAddr type implement **fmt.Stringer** to print dotted ip address
-Test cases for the program

### CODE REVIEW

**Comment by anzboi** [comment]
@eobjects @ShahNikita19 Is this PR ready for review? It has changes requested label with no comments.

**Review by camscale — APPROVED** [review]
LGTM. This is all good code. A couple of points before merging:

1) The linter is not succeeding because your `numeronym_test.go` is too similar to another. I'd suggest just changing the second test input from `"abb a"` to "`abc a"` which will give the same result but should make the linter happy. We'll probably disable that linter check in future.

2) Your stringer test file is named `stringet_test.go`, and should be `stringer_test.go`.

These are both minor, so I'll approve this so you can merge. But it may not work until the linter is happy - not sure.

**Comment by ShahNikita19** [comment]
Yes,  it's ready, can u please review it.

**Comment by juliaogris** [comment]
Please fix broken build!

**Comment by juliaogris** [comment]
Hi,
There has been  no activity in the last 20 days so I will close this PR.
Feel free to open it again if you have something to add.
Thanks!
Julia

**Pull request closed without merging**
