### PR TITLE
Update lab 08_project REAMDE.md

### PR DESCRIPTION
**Pull request by juliaogris**
#### Changes proposed in this PR:
- Remove `go.mod|sum` from required lab 8 project structure
- Remove `vendor` directory from required lab 8 project structure
- Remove `USERNAME` duplication in path

### CODE REVIEW

**Comment by camscale** [comment]
LGTM, but if @n0npax can check and confirm that it all works against his lab, you can merge.

**Review by camscale — APPROVED** [review]
Please wait for @n0npax's confirmation before merging.

**Review by camscale — CHANGES_REQUESTED** [review]
I forgot something. Can you regenerate `labs.md` from the READMEs please.

**Comment by n0npax** [comment]
Lgtm

**Review by n0npax — DISMISSED** [review]

**Review by camscale — APPROVED** [review]
LGTM. Lovely commit message.

**Pull request merged**
