### PR TITLE
Lab 01 - Implement fibonacci series

### PR DESCRIPTION
**Pull request by jecofang01**
Fixes #24 

#### Changes proposed in this PR:

* Implement fibonacci series
* Add test cases
* Fix code style issue

### CODE REVIEW

**Comment by juliaogris** [comment]
Hi @jecofang01 - if you want our labs review, please add `Ready for review` and corresponding lab label to the PR. Also please update your PR description for the other labs like I did for this one. Thanks!

**Review by juliaogris — APPROVED** [review]
I reviewed this pretty quickly, but looks like very solid work. Well done!

**Comment by jecofang01** [comment]
Thank you @juliaogris - I will add the labels in other PR.

**Comment by jecofang01** [comment]
Seems like I don't have access to apply the labels.

**Comment by anzdaddy** [comment]
@jecofang01 Not sure why. I've added you to the go-training team just in case. Try again.

**Pull request merged**
