### PR TITLE
🌱Create PR template

### LINKED ISSUE #2: Create PR template

### PR DESCRIPTION
**Pull request by juliaogris**
Fixes #2 
#### Change proposed in this PR:
Create a simple Github PR template according to [docs](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/).

### CODE REVIEW

**Comment by juliaogris** [comment]
@camh-anz - please re-approve, had to rebase after merging CODEOWNERS.

**Comment by camscale** [comment]
Is this template worth it? There's not much in it. Or is this more intended as a demonstration of a pull request template?

**Comment by juliaogris** [comment]
Another rebase, another re-approval please, @camh-anz . 
:( not sure if this "small-pr" pattern is working out that well.

Maybe I should change the setting that new commits dismiss approvals. But i want that (for the rest of the world). Argh. Torn.

> Is this template worth it? There's not much in it. Or is this more intended as a demonstration of a pull request template?

IMO it is. It forces (or at least encourages) contributors to 
- reference and if necessary create issues
- understand that in Github issues can be referenced as with the hashtag e.g. `#23`
- write a proper PR summary and not just leave it blank.

However I'm not a huge fan of elaborate issue or PR templates.

Either way, if you think it's not worth it - let's just tag it `demonstration`.

**Comment by camscale** [comment]
i think that the details you want in the PR really belong in the commit message. Also if we're considering the multiple small PRs with squash merges rather than one PR with multiple commits to merge, most of the time the template should be "Issue #x" rather than "Fixes #x" as only the last PR is going to fix/close the issue.

But I'll approve this because anything to encourage people to add more details is a good thing. I hope it does encourage them to think about it too, rather than just treat it as boilerplate to get past...

**Review by camscale — APPROVED** [review]

**Pull request merged**
